shell fish
font_family JetBrainsMono Nerd Font
bold_italic_font auto
font_size 9.0
window_padding_width 14
hide_window_decorations yes
confirm_os_window_close 0
cursor_shape beam
shell_integration no-cursor
enable_audio_bell no
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted
map ctrl+v paste_from_clipboard
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard

include theme.conf
cursor_trail 1
